### ISSUE TITLE
irrelevant problem 

### ISSUE THREAD

**Issue by Jigsaw855** [hasherezade/persistence_demos#2]
hi 
I found a method similar that way you provide for persistence via extension hijacking at the flowing address 
https://github.com/cocomelonc/2022-08-26-malware-pers-9
this is how I implemented the method . first I made some change in the hack.cpp file so that it runs my sample code instead of the hack file, then I put the clean up code in the test malware file , in other words I created a bat file in which I did these things

my sample batfile that i executed insted of hack.exe

echo "hello world"
reg add "HKEY_CLASSES_ROOT\txtfile\shell\open\command" /ve /t REG_SZ /d "%SystemRoot%\system32\NOTEPAD.EXE %1

now , I have question , when I change registry by this code (reg add "HKEY_CLASSES_ROOT\txtfile\shell\open\command" /ve /t REG_SZ /d "%SystemRoot%\system32\NOTEPAD.EXE %1) but %1value not show  in a registry and any txt file which I open it after that  showed with untitled headers and I must change registry manually so that %1 inserted in key value to txt file showed correctly

**Comment by Jigsaw855** [comment]
my question is why I  can't  open txt file with it's specific header via this command     "reg add "HKEY_CLASSES_ROOT\txtfile\shell\open\command" /ve /t REG_SZ /d "%SystemRoot%\system32\NOTEPAD.EXE %1"  until i change registry manually and add 1 % in key value

**Comment by hasherezade** [comment]
hi @Jigsaw855 !
It is because %1 in the bat file is treated as a variable to be resolved, not as a literal string. In your script `%1` resolves to an empty string, so it "disappears".
What you should use is double %: `%%1`
So your bat will be the following:

```
echo "hello world"
reg add "HKEY_CLASSES_ROOT\txtfile\shell\open\command" /ve /t REG_SZ /d "%SystemRoot%\system32\NOTEPAD.EXE %%1
```
please let me know if it helped.

**Comment by Jigsaw855** [comment]
thanks great lady
